# Generated by Django 2.2.5 on 2019-10-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0004_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
    ]
