# Generated by Django 2.2.5 on 2019-11-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0008_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
