# Generated by Django 2.2.5 on 2019-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0011_auto_20191106_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.TextField(default=None),
        ),
    ]
