# Generated by Django 2.2.5 on 2019-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0015_auto_20191202_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='Quora/static/images/profile_default.png', null=True, upload_to='Quora/static/images/'),
        ),
    ]
