# Generated by Django 2.2.5 on 2019-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0016_auto_20191202_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.TextField(default=None),
        ),
    ]
